const mongoose = require('mongoose')

const RegisterSchema = new mongoose.Schema(
    {
        createFor:{
            type:String,
            maxLength:50,
            required:true
        },
        username:{
            type:String,
            maxLength:50,
            required:true
 
        },
        email:{
            type:String,
            required:true,
            unique:true
        },
        gender:{
            type:String,
            required:true
        },
        mobilenumber:{
            type:Number,
            required:true,
            unique:true
        },
        dob:{
            type:String,
            default:null
        },
        time_of_birth:{
            type:String,
            default:null
        },
        place_of_birth:{
            type:String,
            required:true
        },
        day_of_birth:{
            type:String,
            required:true
        },
        password:{
            type:String,
            required:true
        },
        family_type:{
            type:String,
            required:true
        },
        father_occupation:{
            type:String,
            required:true
        },
        mother_occupation:{
            type:String,
            required:true
        },
        brother:{
            type:String,
            required:true
        },
        brother_mno:{
            type:String,
            required:true
        },
        sister:{
            type:String,
            required:true
        },
        sister_mno:{
            type:String,
            required:true
        },
        bs_marriage_status:{
            type:String,
        },
        education:{
            type:String,
            required:true
        },
        income:{
            type:String,
            required:true
        },
        employein:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        distric:{
            type:String,
            required:true
        },
        pincode:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true,
            maxLength:50
        },
        height:{
            type:String,
            required:true
        },
        blood_group:{
            type:String,
            required:true
        },
        weight:{
            type:String,
            required:true
        },
        mother_tonque:{
            type:String,
            required:true
        },
        religion:{
            type:String,
            required:true
        },
        caste:{
            type:String,
            required:true
        },
        merried_status:{
            type:String,
            
        },
        maglic: {
            type: String,
            required: true,
        },
        describe:{
            type:String,
            required:true,
            maxLength:200
        },
        updateAt:{
            type:String,
            default:null
        },
        createAt:{
            type:String,
            default:null
        },
        image:{
            type:String,
            required:true
        }

    }
)
const RegisterUser = mongoose.model("RegisterUser", RegisterSchema);
module.exports = RegisterUser;